package models.fixed;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import models.Translation;

import play.data.validation.Constraints.Required;

/**
 * The nationality and all related information.
 *
 * @author Michael Bredel <michael.bredel@fh-kufstein.ac.at>
 */
@Entity
public class Country extends models.Entity {

    /**
     * The serialization version identifier.
     */
    private static final long serialVersionUID = 1L;

    @Id
    @Required
    @GeneratedValue
    long id;

    @Required
    String iso3;

    /**
     * Constructor for Nationality
     */
    public Country(String iso3) {
        this.iso3 = iso3;
    }

    /**
     * Generate the default countries to populate the database initially.
     */
    public static void generateDefault() {
        Country c1 = new Country("ABW");
        Country c2 = new Country("AFG");
        Country c3 = new Country("AGO");
        Country c4 = new Country("AIA");
        Country c5 = new Country("ALA");
        Country c6 = new Country("ALB");
        Country c7 = new Country("AND");
        Country c8 = new Country("ARE");
        Country c9 = new Country("ARG");
        Country c10 = new Country("ARM");
        Country c11 = new Country("ASM");
        Country c12 = new Country("ATA");
        Country c13 = new Country("ATF");
        Country c14 = new Country("ATG");
        Country c15 = new Country("AUS");
        Country c16 = new Country("AUT");
        Country c17 = new Country("AZE");
        Country c18 = new Country("BDI");
        Country c19 = new Country("BEL");
        Country c20 = new Country("BEN");
        Country c21 = new Country("BES");
        Country c22 = new Country("BFA");
        Country c23 = new Country("BGD");
        Country c24 = new Country("BGR");
        Country c25 = new Country("BHR");
        Country c26 = new Country("BHS");
        Country c27 = new Country("BIH");
        Country c28 = new Country("BLM");
        Country c29 = new Country("BLR");
        Country c30 = new Country("BLZ");
        Country c31 = new Country("BMU");
        Country c32 = new Country("BOL");
        Country c33 = new Country("BRA");
        Country c34 = new Country("BRB");
        Country c35 = new Country("BRN");
        Country c36 = new Country("BTN");
        Country c37 = new Country("BVT");
        Country c38 = new Country("BWA");
        Country c39 = new Country("CAF");
        Country c40 = new Country("CAN");
        Country c41 = new Country("CCK");
        Country c42 = new Country("CHE");
        Country c43 = new Country("CHL");
        Country c44 = new Country("CHN");
        Country c45 = new Country("CIV");
        Country c46 = new Country("CMR");
        Country c47 = new Country("COD");
        Country c48 = new Country("COG");
        Country c49 = new Country("COK");
        Country c50 = new Country("COL");
        Country c51 = new Country("COM");
        Country c52 = new Country("CPV");
        Country c53 = new Country("CRI");
        Country c54 = new Country("CUB");
        Country c55 = new Country("CUW");
        Country c56 = new Country("CXR");
        Country c57 = new Country("CYM");
        Country c58 = new Country("CYP");
        Country c59 = new Country("CZE");
        Country c60 = new Country("DEU");
        Country c61 = new Country("DJI");
        Country c62 = new Country("DMA");
        Country c63 = new Country("DNK");
        Country c64 = new Country("DOM");
        Country c65 = new Country("DZA");
        Country c66 = new Country("ECU");
        Country c67 = new Country("EGY");
        Country c68 = new Country("ERI");
        Country c69 = new Country("ESH");
        Country c70 = new Country("ESP");
        Country c71 = new Country("EST");
        Country c72 = new Country("ETH");
        Country c73 = new Country("FIN");
        Country c74 = new Country("FJI");
        Country c75 = new Country("FLK");
        Country c76 = new Country("FRA");
        Country c77 = new Country("FRO");
        Country c78 = new Country("FSM");
        Country c79 = new Country("GAB");
        Country c80 = new Country("GBR");
        Country c81 = new Country("GEO");
        Country c82 = new Country("GGY");
        Country c83 = new Country("GHA");
        Country c84 = new Country("GIB");
        Country c85 = new Country("GIN");
        Country c86 = new Country("GLP");
        Country c87 = new Country("GMB");
        Country c88 = new Country("GNB");
        Country c89 = new Country("GNQ");
        Country c90 = new Country("GRC");
        Country c91 = new Country("GRD");
        Country c92 = new Country("GRL");
        Country c93 = new Country("GTM");
        Country c94 = new Country("GUF");
        Country c95 = new Country("GUM");
        Country c96 = new Country("GUY");
        Country c97 = new Country("HKG");
        Country c98 = new Country("HMD");
        Country c99 = new Country("HND");
        Country c100= new Country("HRV");
        Country c101 = new Country("HTI");
        Country c102 = new Country("HUN");
        Country c103= new Country("IDN");
        Country c104 = new Country("IMN");
        Country c105 = new Country("IND");
        Country c106 = new Country("IOT");
        Country c107 = new Country("IRL");
        Country c108 = new Country("IRN");
        Country c109 = new Country("IRQ");
        Country c110 = new Country("ISL");
        Country c111 = new Country("ISR");
        Country c112 = new Country("ITA");
        Country c113 = new Country("JAM");
        Country c114 = new Country("JEY");
        Country c115 = new Country("JOR");
        Country c116 = new Country("JPN");
        Country c117 = new Country("KAZ");
        Country c118 = new Country("KEN");
        Country c119 = new Country("KGZ");
        Country c120 = new Country("KHM");
        Country c121 = new Country("KIR");
        Country c122 = new Country("KNA");
        Country c123 = new Country("KOR");
        Country c124 = new Country("KWT");
        Country c125 = new Country("LAO");
        Country c126 = new Country("LBN");
        Country c127 = new Country("LBR");
        Country c128 = new Country("LBY");
        Country c129 = new Country("LCA");
        Country c130 = new Country("LIE");
        Country c131 = new Country("LKA");
        Country c132 = new Country("LSO");
        Country c133 = new Country("LTU");
        Country c134 = new Country("LUX");
        Country c135 = new Country("LVA");
        Country c136 = new Country("MAC");
        Country c137 = new Country("MAF");
        Country c138 = new Country("MAR");
        Country c139 = new Country("MCO");
        Country c140 = new Country("MDA");
        Country c141 = new Country("MDG");
        Country c142 = new Country("MDV");
        Country c143 = new Country("MEX");
        Country c144 = new Country("MHL");
        Country c145 = new Country("MKD");
        Country c146 = new Country("MLI");
        Country c147 = new Country("MLT");
        Country c148 = new Country("MMR");
        Country c149 = new Country("MNE");
        Country c150 = new Country("MNG");
        Country c151 = new Country("MNP");
        Country c152 = new Country("MOZ");
        Country c153 = new Country("MRT");
        Country c154 = new Country("MSR");
        Country c155 = new Country("MTQ");
        Country c156 = new Country("MUS");
        Country c157 = new Country("MWI");
        Country c158 = new Country("MYS");
        Country c159 = new Country("MYT");
        Country c160 = new Country("NAM");
        Country c161 = new Country("NCL");
        Country c162 = new Country("NER");
        Country c163 = new Country("NFK");
        Country c164 = new Country("NGA");
        Country c165 = new Country("NIC");
        Country c166 = new Country("NIU");
        Country c167 = new Country("NLD");
        Country c168 = new Country("NOR");
        Country c169 = new Country("NPL");
        Country c170 = new Country("NRU");
        Country c171 = new Country("NZL");
        Country c172 = new Country("OMN");
        Country c173 = new Country("PAK");
        Country c174 = new Country("PAN");
        Country c175 = new Country("PCN");
        Country c176 = new Country("PER");
        Country c177 = new Country("PHL");
        Country c178 = new Country("PLW");
        Country c179 = new Country("PNG");
        Country c180 = new Country("POL");
        Country c181 = new Country("PRI");
        Country c182 = new Country("PRK");
        Country c183 = new Country("PRT");
        Country c184 = new Country("PRY");
        Country c185 = new Country("PSE");
        Country c186 = new Country("PYF");
        Country c187 = new Country("QAT");
        Country c188 = new Country("REU");
        Country c189 = new Country("ROU");
        Country c190 = new Country("RUS");
        Country c191 = new Country("RWA");
        Country c192 = new Country("SAU");
        Country c193 = new Country("SDN");
        Country c194 = new Country("SEN");
        Country c195 = new Country("SGP");
        Country c196 = new Country("SGS");
        Country c197 = new Country("SHN");
        Country c198 = new Country("SJM");
        Country c199 = new Country("SLB");
        Country c200 = new Country("SLE");
        Country c201 = new Country("SLV");
        Country c202 = new Country("SMR");
        Country c203 = new Country("SOM");
        Country c204 = new Country("SPM");
        Country c205 = new Country("SRB");
        Country c206 = new Country("SSD");
        Country c207 = new Country("STP");
        Country c208 = new Country("SUR");
        Country c209 = new Country("SVK");
        Country c210 = new Country("SVN");
        Country c211 = new Country("SWE");
        Country c212 = new Country("SWZ");
        Country c213 = new Country("SXM");
        Country c214 = new Country("SYC");
        Country c215 = new Country("SYR");
        Country c216 = new Country("TCA");
        Country c217 = new Country("TCD");
        Country c218 = new Country("TGO");
        Country c219 = new Country("THA");
        Country c220 = new Country("TJK");
        Country c221 = new Country("TKL");
        Country c222 = new Country("TKM");
        Country c223 = new Country("TLS");
        Country c224 = new Country("TON");
        Country c225 = new Country("TTO");
        Country c226 = new Country("TUN");
        Country c227 = new Country("TUR");
        Country c228 = new Country("TUV");
        Country c229 = new Country("TWN");
        Country c230 = new Country("TZA");
        Country c231 = new Country("UGA");
        Country c232 = new Country("UKR");
        Country c233 = new Country("UMI");
        Country c234 = new Country("URY");
        Country c235 = new Country("USA");
        Country c236 = new Country("UZB");
        Country c237 = new Country("VAT");
        Country c238 = new Country("VCT");
        Country c239 = new Country("VEN");
        Country c240 = new Country("VGB");
        Country c241 = new Country("VIR");
        Country c242 = new Country("VNM");
        Country c243 = new Country("VUT");
        Country c244 = new Country("WLF");
        Country c245 = new Country("WSM");
        Country c246 = new Country("YEM");
        Country c247 = new Country("ZAF");
        Country c248 = new Country("ZMB");
        Country c249 = new Country("ZWE");
        
        c1.save();
        c2.save();
        c3.save();
        c4.save();
        c5.save();
        c6.save();
        c7.save();
        c8.save();
        c9.save();
        c10.save();
        c11.save();
        c12.save();
        c13.save();
        c14.save();
        c15.save();
        c16.save();
        c17.save();
        c18.save();
        c19.save();
        c20.save();
        c21.save();
        c22.save();
        c23.save();
        c24.save();
        c25.save();
        c26.save();
        c27.save();
        c28.save();
        c29.save();
        c30.save();
        c31.save();
        c32.save();
        c33.save();
        c34.save();
        c35.save();
        c36.save();
        c37.save();
        c38.save();
        c39.save();
        c40.save();
        c41.save();
        c42.save();
        c43.save();
        c44.save();
        c45.save();
        c46.save();
        c47.save();
        c48.save();
        c49.save();
        c50.save();
        c51.save();
        c52.save();
        c53.save();
        c54.save();
        c55.save();
        c56.save();
        c57.save();
        c58.save();
        c59.save();
        c60.save();
        c61.save();
        c62.save();
        c63.save();
        c64.save();
        c65.save();
        c66.save();
        c67.save();
        c68.save();
        c69.save();
        c70.save();
        c71.save();
        c72.save();
        c73.save();
        c74.save();
        c75.save();
        c76.save();
        c77.save();
        c78.save();
        c79.save();
        c80.save();
        c81.save();
        c82.save();
        c83.save();
        c84.save();
        c85.save();
        c86.save();
        c87.save();
        c88.save();
        c89.save();
        c90.save();
        c91.save();
        c92.save();
        c93.save();
        c94.save();
        c95.save();
        c96.save();
        c97.save();
        c98.save();
        c99.save();
        c100.save();
        c101.save();
        c102.save();
        c103.save();
        c104.save();
        c105.save();
        c106.save();
        c107.save();
        c108.save();
        c109.save();
        c110.save();
        c111.save();
        c112.save();
        c113.save();
        c114.save();
        c115.save();
        c116.save();
        c117.save();
        c118.save();
        c119.save();
        c120.save();
        c121.save();
        c122.save();
        c123.save();
        c124.save();
        c125.save();
        c126.save();
        c127.save();
        c128.save();
        c129.save();
        c130.save();
        c131.save();
        c132.save();
        c133.save();
        c134.save();
        c135.save();
        c136.save();
        c137.save();
        c138.save();
        c139.save();
        c140.save();
        c141.save();
        c142.save();
        c143.save();
        c144.save();
        c145.save();
        c146.save();
        c147.save();
        c148.save();
        c149.save();
        c150.save();
        c151.save();
        c152.save();
        c153.save();
        c154.save();
        c155.save();
        c156.save();
        c157.save();
        c158.save();
        c159.save();
        c160.save();
        c161.save();
        c162.save();
        c163.save();
        c164.save();
        c165.save();
        c166.save();
        c167.save();
        c168.save();
        c169.save();
        c170.save();
        c171.save();
        c172.save();
        c173.save();
        c174.save();
        c175.save();
        c176.save();
        c177.save();
        c178.save();
        c179.save();
        c180.save();
        c181.save();
        c182.save();
        c183.save();
        c184.save();
        c185.save();
        c186.save();
        c187.save();
        c188.save();
        c189.save();
        c190.save();
        c191.save();
        c192.save();
        c193.save();
        c194.save();
        c195.save();
        c196.save();
        c197.save();
        c198.save();
        c199.save();
        c200.save();
        c201.save();
        c202.save();
        c203.save();
        c204.save();
        c205.save();
        c206.save();
        c207.save();
        c208.save();
        c209.save();
        c210.save();
        c211.save();
        c212.save();
        c213.save();
        c214.save();
        c215.save();
        c216.save();
        c217.save();
        c218.save();
        c219.save();
        c220.save();
        c221.save();
        c222.save();
        c223.save();
        c224.save();
        c225.save();
        c226.save();
        c227.save();
        c228.save();
        c229.save();
        c230.save();
        c231.save();
        c232.save();
        c233.save();
        c234.save();
        c235.save();
        c236.save();
        c237.save();
        c238.save();
        c239.save();
        c240.save();
        c241.save();
        c242.save();
        c243.save();
        c244.save();
        c245.save();
        c246.save();
        c247.save();
        c248.save();
        c249.save();
        
    }
}
